---
- hosts: all
  become: true
  tasks:

  - name: install and update package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes